os: linux
dist: trusty
language: node_js
cache:
  yarn: true
  directories:
  - node_modules
  - "/home/travis/.cache/Cypress"
node_js:
- lts/*
- 10
before_install:
- export TZ='Asia/Shanghai'
- npm i -g yarn
- npm i -g nyc
- npm i -g conventional-github-releaser
- npm i -g conventional-changelog-cli
install:
- yarn
- cypress install
script:
- npm run build
- npm run test:e2e-ci
- npm run test:unit
- npm run coverage
deploy:
- provider: pages
  skip_cleanup: 'true'
  github_token:
    secure: fdBIUuTH1oB3B/EoW2w/EFQZFjN+oB5tE78OTgpxsO4yWe5Oi9Sppa4blx96wW8lEc9vT0xNas2E6mtKzaQiXAG7FNUn0ovh8wqxjeFQeNldBCzwSuz0ofkNs0kBw9jwIh1QEeAHv8Ona74aFO/KSUcC62I5XTrLJx58ymrRS7UrMxoe0hkUVjAHoR00Z9eEoxEVHK4jed/41G23ws78Ik7vxWxIENHzpLb3Q25kWK78CzrknuTemj785zt54qheAL9me85gqx4mwXHj97AefapzRce8H/7bTb/bkLCbn91VvuNIbPy2y+uvu7TVktlhHQtauI3wlbyV/qkWBqvUBFg3m5Ca2kYkr5r/SkKEgzya81o6hqSBbYmnr/enSnfEEVjDVK7AdMA48YMMCs4uu56MDnbwYYcXbV1GfbfltmNjpl5GAfNWJVVG3h/dL/HCG3gg3i3bWjTAwOC0WYMcd86/wxXWufQ1xXsKZlUqR2pFg5lF0tOjbDJdIjihlQaJEPVJBNGYS68RNpI4aAGwOv2YkxDVOw21fZVSkNozRpiruN0r9NE66o2N+DyxA5lQz/Kw+/aFgk3HBGv/L74N8Nen+NPofJKyFeqkqelYpVnMwvXAnjgMDZhqAV2Og/0Ku69uN2gZ5Y2+u/3/RsnWOLVl9ZNl++XZu4belG+T840=
  local_dir: docs
  on:
    repo: awamwang/vue-form-gen
    branch: doc
- provider: npm
  skip_cleanup: 'true'
  email: wangnew2013@126.com
  api_key:
    secure: W/BEK6eAEna6JVCZYgKIwyu2mqXa83oR/jDNEapt6i59Ajx/wyKLxuE6+W4Xl9Sl9hqgFb8XcLw6L6TUrAhr+uk0mipYj/yxBY2xAen/lkm+IAoMgl3p2XE99oLHCsf1iT3FEmDvN/t28sNLlrkyfqZROWPHGFBd5GzdMgbm86njFgEv1jmaGLpBVnUBrBHv4+5/eFiiKcaWMOoteF7vjHJRIMbsuf5yfBR7RnbcS2y8zdexKVAVUFqYUfaUTfuB+vG9+G5aNmPXVBExGx2H5obpM1b6qwizJMzw0UEwPDGmIdrpEWEiV6GyfWgP4CorOUnSgoJ0cqW0SLxfKQ60f6XOGamEUTZfuaAzFWnsy6R44s9P/MW11UTnpJ/AMMtRzitZL7GhAl61VtEuxQaIdbjg8Zw/A3TgbegjPFJMR9WJjd7i2ARImT+bxKzBdwn2thGLDHgh53BnP/J7V8BV8okPV2WY3C/nKSGs8ok5CpoEnRXJe/8ewRQMdtDmjk9kzhlZGVNLH5kYcBJmFaB0Rsjh85PR3ODIr3MVw9LMlIZmzSKVTogoLCodpfPKDF40lHNstHlWduwATOPo6uOqmg9Q8mXq59lqbedayn7j495i54LqdHlAQGbF+d6Ar8utAuf84L054aLUYys5l2W+EWZZ2lzHGe4fUeMBlSsgKig=
  on:
    tags: true
    repo: awamwang/vue-form-gen
env:
  global:
    secure: gg7ozHXDl8W/EMWUYGdzlv0dKfCSk8xUwPMHAMTXEJucNnGJOTVaEmgZCjnK6tm4M679ULtnjKU1bfcLZqW//pWD2o1NSFNh4OGUWxYVGTdOXJTqikzLgaZpCsH0DUAY6StDiN1OVaog/RmSp9Kn7e3k+W7pKFuGKttamAXrX0zzxbDQLCExyKEoLj/jqE5wfX7mfOIsLUdu5XxhQyK2pscW00BwSfg2faahFBZHu93W3gZo9QZ6RiSgpP72qi+6DB+i+wOcyCpCngZ9QeGei84WBKj4bg457NDU478EoGTdNamaWo6CMZim8c63SWHmjiYdRM8ATaBULY0xeqYxEm0x1UcC9To4kUz6hmOHDz7ueubGV9jwOq9uQF0fd9lLKMyNYKR/i6+kQplTTB4s3TyrTVsdi1qjnzuCF356OVFQvF02yr3gMG6waQV9MhqQMAPJTWNMm1bRizFbmODMjDtYT61rHKfx9+NP+IO/K70CwGj97WcdlH3QNgO4TBcqU24pAz6GnwmI3IKHsBFDWuwLeNY3imMDT1QTZBlk8hbtZAbDI+VPmI6dwqwV9IanW9BY8z15zTBX86lYLsnUrrd2ZOAnu50gqBiZDVgiWLJZl4jKvR5cYLLdnueH+umKsjSiQyh1OFjnRWB5U5jCHUbW/8h/PVGR4j/9joQV0m0=
after_deploy: DEBUG=conventional-github-releaser conventional-github-releaser -p angular -r 1 -t $GH_TOKEN
