os: linux
dist: trusty
language: node_js
cache:
  yarn: true
  directories:
  - node_modules
  - "/home/travis/.cache/Cypress"
node_js:
- lts/*
- 10
before_install:
- export TZ='Asia/Shanghai'
- npm i -g yarn
- npm i -g nyc
- npm i -g conventional-github-releaser
- npm i -g conventional-changelog-cli
install:
- npm run bootstrap
- cypress install
script:
- npm run build
- npm run test
after_script:
- npm run coverage
deploy:
- provider: pages
  strategy: git
  token:
    secure: fdBIUuTH1oB3B/EoW2w/EFQZFjN+oB5tE78OTgpxsO4yWe5Oi9Sppa4blx96wW8lEc9vT0xNas2E6mtKzaQiXAG7FNUn0ovh8wqxjeFQeNldBCzwSuz0ofkNs0kBw9jwIh1QEeAHv8Ona74aFO/KSUcC62I5XTrLJx58ymrRS7UrMxoe0hkUVjAHoR00Z9eEoxEVHK4jed/41G23ws78Ik7vxWxIENHzpLb3Q25kWK78CzrknuTemj785zt54qheAL9me85gqx4mwXHj97AefapzRce8H/7bTb/bkLCbn91VvuNIbPy2y+uvu7TVktlhHQtauI3wlbyV/qkWBqvUBFg3m5Ca2kYkr5r/SkKEgzya81o6hqSBbYmnr/enSnfEEVjDVK7AdMA48YMMCs4uu56MDnbwYYcXbV1GfbfltmNjpl5GAfNWJVVG3h/dL/HCG3gg3i3bWjTAwOC0WYMcd86/wxXWufQ1xXsKZlUqR2pFg5lF0tOjbDJdIjihlQaJEPVJBNGYS68RNpI4aAGwOv2YkxDVOw21fZVSkNozRpiruN0r9NE66o2N+DyxA5lQz/Kw+/aFgk3HBGv/L74N8Nen+NPofJKyFeqkqelYpVnMwvXAnjgMDZhqAV2Og/0Ku69uN2gZ5Y2+u/3/RsnWOLVl9ZNl++XZu4belG+T840=
  local_dir: docs
  on:
    repo: awamwang/vue-form-gen
    branch: doc
  cleanup: 'true'
- provider: npm
  email: wm.keepgoing@gmail.com
  api_token:
    secure: XD7F89zpQjQaw41qZYSWt5MhcxyGm3zOUtO1m8Lu6FPwvFMrf9E++FHmhojI4TyshlJc8g4zmZZVUNkHu2gxdw7U3ptmxaZzLY3W/sxv61nAxc/fQWMj4tcu3xFMlRxbxcCALJ17hNEQE6Q044WTVggvrDgfDqQwhAT6+qC5MmFIJ7kJ3E7Cqgeu+/vbQktSnZRVU/rg36XvGeAwq9AIFTJ0kmjUBot30eXh+G/ABufEeADfXxTlRAvhAcVmERZdRnGVBF3mxfj+DoEVNigM9o1rIVPa9KyJfGdKZwEmtZAkAVA0X4fKAj+1/mdKtqqTpyqWNZOf/SXEhqGkpqf8cQ7Bwi2bWBld0GTc5Dwhxi4g54pZ8qAsmietwRfGmBCXjDusvP3bBhsj54hJhHJlfjp3fobeLZp5t1xHhF0+k6cxlnolkDvIfJPzyMRdzkWJpsAUgDU8aiEzNfbAkxdUMhYSc8rzkD6MllHgA18h3MIHg/WVWL0XEWIoGrl5rZEYKdxu0wEj9FbfVoXZM7jTCSfsJF9iZ0FwqMjvqX4JDpoakRWu2K0z2xMzgxPjDOzR7KqjwrsU6qHPVYIV+1g5i+5k0LaV8NBLvOBQK5+qEbQp0DrQGrPmwim8c8upPkcxulhQGKVDOPnQ7ohwa5Q7XAHYaOc0d1XGqGWPW8+XAyA=
  on:
    tags: true
    repo: awamwang/vue-form-gen
  cleanup: 'true'
after_deploy: DEBUG=conventional-github-releaser conventional-github-releaser -p angular -r 1 -t $GH_TOKEN
env:
  global:
  - secure: gg7ozHXDl8W/EMWUYGdzlv0dKfCSk8xUwPMHAMTXEJucNnGJOTVaEmgZCjnK6tm4M679ULtnjKU1bfcLZqW//pWD2o1NSFNh4OGUWxYVGTdOXJTqikzLgaZpCsH0DUAY6StDiN1OVaog/RmSp9Kn7e3k+W7pKFuGKttamAXrX0zzxbDQLCExyKEoLj/jqE5wfX7mfOIsLUdu5XxhQyK2pscW00BwSfg2faahFBZHu93W3gZo9QZ6RiSgpP72qi+6DB+i+wOcyCpCngZ9QeGei84WBKj4bg457NDU478EoGTdNamaWo6CMZim8c63SWHmjiYdRM8ATaBULY0xeqYxEm0x1UcC9To4kUz6hmOHDz7ueubGV9jwOq9uQF0fd9lLKMyNYKR/i6+kQplTTB4s3TyrTVsdi1qjnzuCF356OVFQvF02yr3gMG6waQV9MhqQMAPJTWNMm1bRizFbmODMjDtYT61rHKfx9+NP+IO/K70CwGj97WcdlH3QNgO4TBcqU24pAz6GnwmI3IKHsBFDWuwLeNY3imMDT1QTZBlk8hbtZAbDI+VPmI6dwqwV9IanW9BY8z15zTBX86lYLsnUrrd2ZOAnu50gqBiZDVgiWLJZl4jKvR5cYLLdnueH+umKsjSiQyh1OFjnRWB5U5jCHUbW/8h/PVGR4j/9joQV0m0=
  - secure: jH1fX4lIcuKb9QO5SGb2pF0aGzEHDKgYSWZUss31N1ht/EfMqtLUkudVzdoJrIQQugWEBlWUmfRjjraaNovk2Q5cqiSCGOVcOKtE+ClDYhvkSMvGcLbwGnhy7CZEiuN/bcTUVrX8cLPPSDZgeTPJlJNz4sdy32NDXke429eOloRfZ3eJ4OgqMWKvW6wZKLc0R3MRcnCgwByyjajh4HBJt++79VcPaykexey2fLM88Br98fYLmPM8C4Lf33pcD8QcrhHUJkvq8UyCA8rSI0YpV8avDr8ZUnaAZRjxO7C1cjcJ6R6w0vWLHAqetiYsi+wKWqxetFFijVnmL6mtQl95ekQtr9ih9VccmciBHUtHLBOxD/m9qWsjVne93c8ydhngHrqoqZds5guYHXgrTc6fyHhuypKTSFkJLpWigu8REJ0FPyrYuoeWci+EhoD+8+zGlGXeUWkehbp0nWpo2WMwqqoUT1Vx+9aalRyHTHShvJdxvGK/Rd97Sd6MskiNlQ3jd/Uf0D1TeMEvo7tOqdt/lYYxQwHcmuwVt29qrgD16VH1lDXZxRDMqc3Yv0IwyxJVHQS4alGCW51qHGgEaGb74pHvmJwuaScqRWZJ2ObGnl+Ai9YRf6PLLS5eMa3Kud+WuLXW2nv8hALlXEDFHDxt6muE73//UZ42o2OrhsV6Qi0=
